# Generated by Django 5.0.6 on 2024-06-26 12:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_jerk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='UserProfile',
        ),
    ]
