# Generated by Django 5.0.6 on 2024-05-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbastards', '0005_alter_members_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
