# Generated by Django 5.0.6 on 2024-05-31 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbastards', '0008_remove_members_post_posts_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitbastards.members'),
        ),
    ]
