# Generated by Django 5.0.6 on 2024-05-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbastards', '0009_alter_posts_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
